FILE_HEADER = """\
// Auto-generated by api-generator
// Do not edit manually
"""

IMPORT_HEADER = """\
import { apiClient } from './client';
import type {\
"""

IMPORT_FOOTER = "} from './types';"

CONTROLLER_OPEN = "export const {controller}Api = {{"
CONTROLLER_CLOSE = "};"
CONTROLLER_COMMENT = "// {controller} API"
