# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
variable "region" { # tflint-ignore: terraform_unused_declarations
  description = "AWS Region"
  type        = string
  default     = "ap-northeast-1"
}

variable "env_name" { # tflint-ignore: terraform_unused_declarations
  description = "Deployment Environment"
  type        = string
  default     = "prod"
}

variable "app_name" { # tflint-ignore: terraform_unused_declarations
  description = "Application Name"
  type        = string
  default     = "nari-note"
}

variable "state_bucket_name" { # tflint-ignore: terraform_unused_declarations
  description = "S3 Bucket for Terraform State"
  type        = string
  default     = "nari-note-terraform"
}
