"""
endpoints.ts生成用テンプレート
"""

from typing import List, Dict
from models import CSharpClass, EndpointInfo
from .base import BaseTemplate


class EndpointsTemplate(BaseTemplate):
    """endpoints.ts生成用テンプレート"""

    def __init__(self, value_object_types: set[str], class_map: Dict[str, CSharpClass]):
        super().__init__(value_object_types)
        self.class_map = class_map

    def get_header(self) -> str:
        return """// Auto-generated by api-generator.py
// Do not edit manually

import { apiClient } from './client';
import type {"""

    def generate(self, endpoints: List[EndpointInfo]) -> str:
        """
        完全なendpoints.tsの内容を生成

        Args:
            endpoints: エンドポイント情報のリスト

        Returns:
            endpoints.tsの完全な内容
        """
        lines = [self.get_header()]

        # 型インポートを生成
        lines.extend(self._generate_type_imports(endpoints))
        lines.append("")

        # コントローラー別のAPI関数を生成
        by_controller = self._group_by_controller(endpoints)
        for controller, eps in sorted(by_controller.items()):
            lines.extend(self._generate_controller_api(controller, eps))
            lines.append("")

        return self._join_lines(lines)

    def _generate_type_imports(self, endpoints: List[EndpointInfo]) -> List[str]:
        """型インポートセクションを生成"""
        all_types = self._collect_types_from_endpoints(endpoints)
        return [f"  {type_name}," for type_name in sorted(all_types)] + ["} from './types';"]

    def _generate_controller_api(self, controller: str, endpoints: List[EndpointInfo]) -> List[str]:
        """コントローラーごとのAPIオブジェクトを生成"""
        lines = []
        lines.append(f"// {controller.capitalize()} API")
        lines.append(f"export const {controller}Api = {{")

        for ep in endpoints:
            lines.extend(self._generate_api_function(ep))

        lines.append("};")

        return lines

    def _generate_api_function(self, ep: EndpointInfo) -> List[str]:
        """個別のAPI関数を生成"""
        lines = []

        func_name = self._to_camel_case(ep.function_name)
        request_type = ep.request_type or "void"
        response_type = ep.response_type or "void"

        # パスパラメータを検出
        path_params = self._extract_path_params(ep.path)

        # URL式を構築
        if path_params:
            url_path = ep.path
            for param in path_params:
                resolved_param = self._resolve_path_param(param, request_type, self.class_map)
                url_path = url_path.replace(f'{{{param}}}', f'${{data.{resolved_param}}}')
            url_expression = f"`{url_path}`"
        else:
            url_expression = f"'{ep.path}'"

        # API関数を生成
        send_body = ep.has_body_param or (not path_params and request_type != "void")

        if request_type == "void":
            lines.append(f"  {func_name}: async (): Promise<{response_type}> => {{")
            if ep.method == "DELETE":
                lines.append(f"    await apiClient.delete({url_expression});")
            elif ep.method == "GET":
                lines.append(f"    const response = await apiClient.get<{response_type}>({url_expression});")
                lines.append("    return response;")
            else:
                lines.append(f"    const response = await apiClient.{ep.method.lower()}<{response_type}>({url_expression});")
                lines.append("    return response;")
        else:
            lines.append(f"  {func_name}: async (data: {request_type}): Promise<{response_type}> => {{")
            if ep.method == "DELETE":
                lines.append(f"    await apiClient.delete({url_expression});")
            elif ep.method == "GET":
                if path_params:
                    lines.append(f"    const response = await apiClient.get<{response_type}>({url_expression});")
                else:
                    lines.append(f"    const response = await apiClient.get<{response_type}>({url_expression}, {{ params: data }});")
                lines.append("    return response;")
            else:
                if send_body:
                    lines.append(f"    const response = await apiClient.{ep.method.lower()}<{response_type}>({url_expression}, data);")
                else:
                    lines.append(f"    const response = await apiClient.{ep.method.lower()}<{response_type}>({url_expression});")
                lines.append("    return response;")

        lines.append("  },")

        return lines
