"""
hooks.ts生成用テンプレート
"""

from typing import List
from models import EndpointInfo
from .base import BaseTemplate


class HooksTemplate(BaseTemplate):
    """hooks.ts生成用テンプレート"""

    def get_header(self) -> str:
        return """// Auto-generated by api-generator.py
// Do not edit manually

import { useMutation, useQuery, useQueryClient, type UseMutationOptions, type UseQueryOptions } from '@tanstack/react-query';"""

    def generate(self, endpoints: List[EndpointInfo]) -> str:
        """
        完全なhooks.tsの内容を生成

        Args:
            endpoints: エンドポイント情報のリスト

        Returns:
            hooks.tsの完全な内容
        """
        lines = [self.get_header()]

        # インポートを生成
        lines.extend(self._generate_imports(endpoints))
        lines.append("")

        # Query Keysを生成
        lines.extend(self._generate_query_keys(endpoints))
        lines.append("")

        # フックを生成
        by_controller = self._group_by_controller(endpoints)
        for controller, eps in sorted(by_controller.items()):
            lines.extend(self._generate_hooks(controller, eps))

        return self._join_lines(lines)

    def _generate_imports(self, endpoints: List[EndpointInfo]) -> List[str]:
        """インポート文を生成"""
        lines = []

        # コントローラーごとにグループ化してインポート
        by_controller = self._group_by_controller(endpoints)
        controller_imports = ", ".join([f"{c}Api" for c in sorted(by_controller.keys())])
        lines.append(f"import {{ {controller_imports} }} from './endpoints';")

        # 型のインポート
        all_types = set()
        for ep in endpoints:
            if ep.request_type and ep.request_type != "void":
                all_types.add(ep.request_type)
            if ep.response_type and ep.response_type != "void":
                all_types.add(ep.response_type)

        if all_types:
            lines.append("import type {")
            for type_name in sorted(all_types):
                lines.append(f"  {type_name},")
            lines.append("} from './types';")

        return lines

    def _generate_query_keys(self, endpoints: List[EndpointInfo]) -> List[str]:
        """Query Keysセクションを生成"""
        lines = []
        lines.append("// Query Keys")
        lines.append("export const queryKeys = {")

        by_controller = self._group_by_controller(endpoints)
        for controller in sorted(by_controller.keys()):
            lines.append(f"  {controller}: {{")
            for ep in by_controller[controller]:
                if ep.method == "GET":
                    func_name = self._to_camel_case(ep.function_name)
                    lines.append(f"    {func_name}: ['{controller}', '{func_name}'] as const,")
            lines.append("  },")

        lines.append("};")

        return lines

    def _generate_hooks(self, controller: str, endpoints: List[EndpointInfo]) -> List[str]:
        """コントローラーごとのフックを生成"""
        lines = []
        lines.append(f"// {controller.capitalize()} Hooks")

        for ep in endpoints:
            func_name = self._to_camel_case(ep.function_name)
            hook_name = f"use{ep.function_name}"

            if ep.method == "GET":
                # Query hook
                lines.extend(self._generate_query_hook(ep, hook_name, func_name, controller))
                lines.append("")
            else:
                # Mutation hook
                lines.extend(self._generate_mutation_hook(ep, hook_name, func_name, controller))
                lines.append("")

        return lines

    def _generate_query_hook(self, ep: EndpointInfo, hook_name: str, func_name: str, controller: str) -> List[str]:
        """Queryフックを生成"""
        lines = []

        return_type = ep.response_type or "void"
        request_type = ep.request_type or "void"

        if request_type == "void":
            lines.append(f"export function {hook_name}(options?: Omit<UseQueryOptions<{return_type}>, 'queryKey' | 'queryFn'>) {{")
            lines.append(f"  return useQuery<{return_type}>({{")
            lines.append(f"    queryKey: queryKeys.{controller}.{func_name},")
            lines.append(f"    queryFn: () => {controller}Api.{func_name}(),")
            lines.append("    ...options,")
            lines.append("  });")
            lines.append("}")
        else:
            lines.append(f"export function {hook_name}(params: {request_type}, options?: Omit<UseQueryOptions<{return_type}>, 'queryKey' | 'queryFn'>) {{")
            lines.append(f"  return useQuery<{return_type}>({{")
            lines.append(f"    queryKey: [...queryKeys.{controller}.{func_name}, params],")
            lines.append(f"    queryFn: () => {controller}Api.{func_name}(params),")
            lines.append("    ...options,")
            lines.append("  });")
            lines.append("}")

        return lines

    def _generate_mutation_hook(self, ep: EndpointInfo, hook_name: str, func_name: str, controller: str) -> List[str]:
        """Mutationフックを生成"""
        lines = []

        request_type = ep.request_type or "void"
        response_type = ep.response_type or "void"

        if request_type == "void":
            # request_type が void の場合は引数なし
            lines = [
                f"export function {hook_name}(options?: UseMutationOptions<{response_type}, Error, {request_type}>) {{",
                "  const queryClient = useQueryClient();",
                f"  return useMutation<{response_type}, Error, {request_type}>({{",
                f"    mutationFn: () => {controller}Api.{func_name}(),",
                "    onSuccess: (...args) => {",
                f"      queryClient.invalidateQueries({{ queryKey: ['{controller}'] }});",
                "      options?.onSuccess?.(...args);",
                "    },",
                "    ...options,",
                "  });",
                "}",
            ]
        else:
            lines = [
                f"export function {hook_name}(options?: UseMutationOptions<{response_type}, Error, {request_type}>) {{",
                "  const queryClient = useQueryClient();",
                f"  return useMutation<{response_type}, Error, {request_type}>({{",
                f"    mutationFn: (data) => {controller}Api.{func_name}(data),",
                "    onSuccess: (...args) => {",
                f"      queryClient.invalidateQueries({{ queryKey: ['{controller}'] }});",
                "      options?.onSuccess?.(...args);",
                "    },",
                "    ...options,",
                "  });",
                "}",
            ]

        return lines
