"""
types.ts生成用テンプレート
"""

from typing import List
from models import CSharpClass
from helpers import csharp_type_to_typescript
from .base import BaseTemplate


class TypesTemplate(BaseTemplate):
    """types.ts生成用テンプレート"""

    def get_header(self) -> str:
        return """// Auto-generated by api-generator.py
// Do not edit manually
"""

    def generate(self, classes: List[CSharpClass]) -> str:
        """
        完全なtypes.tsの内容を生成

        Args:
            classes: C#クラスのリスト

        Returns:
            types.tsの完全な内容
        """
        lines = [self.get_header(), ""]

        for cls in sorted(classes, key=lambda x: x.name):
            lines.extend(self._generate_interface(cls))
            lines.append("")

        return self._join_lines(lines)

    def _generate_interface(self, cls: CSharpClass) -> List[str]:
        """インターフェース全体を生成"""
        lines = []

        # 空インターフェースの場合はeslint-disableを追加
        if not cls.properties:
            lines.append("// eslint-disable-next-line @typescript-eslint/no-empty-object-type")

        lines.append(f"export interface {cls.name} {{")

        # プロパティ生成
        for prop in cls.properties:
            ts_type, is_nullable = csharp_type_to_typescript(prop.type, self.value_object_types)
            is_optional = is_nullable or prop.is_optional
            camel_name = self._to_camel_case(prop.name)
            optional = "?" if is_optional else ""
            lines.append(f"  {camel_name}{optional}: {ts_type};")

        lines.append("}")
        return lines
