source "https://rubygems.org"

gem "rails", "~> 8.0.2"
# gem "bcrypt", "~> 3.1.7"

# Middleware
gem "puma", ">= 5.0"

# Database
gem "mysql2", "~> 0.5"
gem "solid_cache"
gem "activerecord-import"

# Launch
gem "bootsnap", require: false

# Util
gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "stringio", "3.1.7"

group :development, :test do
  gem "pry", require: false
  gem "pry-byebug", require: false
  gem "pry-rails", require: false
  gem "brakeman", require: false
end

group :development do
  gem "rubocop", require: false
  gem "rubocop-rails", require: false
  gem "rubocop-rails-omakase", require: false
  gem "rubocop-performance", require: false
end
