// Auto-generated API endpoint functions
// DO NOT EDIT MANUALLY - generated by api-generator.py

import { apiClient } from './client';
import type {

  AuthResponse,
  CreateArticleRequest,
  CreateArticleResponse,
  DeleteArticleRequest,
  GetArticleRequest,
  GetArticleResponse,
  GetArticlesByAuthorRequest,
  GetArticlesByAuthorResponse,
  GetArticlesByTagRequest,
  GetArticlesByTagResponse,
  GetArticlesRequest,
  GetArticlesResponse,
  GetDraftArticlesRequest,
  GetDraftArticlesResponse,
  GetHealthResponse,
  GetUserProfileRequest,
  GetUserProfileResponse,
  SignInRequest,
  SignUpRequest,
  ToggleLikeRequest,
  ToggleLikeResponse,
  UpdateArticleRequest,
  UpdateArticleResponse,
  UpdateUserProfileRequest,
  UpdateUserProfileResponse,
} from './types';

// Articles API
export const articlesApi = {
  getArticles: async (data: GetArticlesRequest): Promise<GetArticlesResponse> => {
    return apiClient.get('/api/articles', { params: data });
  },
  createArticle: async (data: CreateArticleRequest): Promise<CreateArticleResponse> => {
    return apiClient.post('/api/articles', data);
  },
  getArticle: async (data: GetArticleRequest): Promise<GetArticleResponse> => {
    return apiClient.get(`/api/articles/${data.id}`, { params: data });
  },
  updateArticle: async (data: UpdateArticleRequest): Promise<UpdateArticleResponse> => {
    return apiClient.put(`/api/articles/${data.id}`, data);
  },
  getArticlesByAuthor: async (data: GetArticlesByAuthorRequest): Promise<GetArticlesByAuthorResponse> => {
    return apiClient.get(`/api/articles/author/${data.authorId}`, { params: data });
  },
  getArticlesByTag: async (data: GetArticlesByTagRequest): Promise<GetArticlesByTagResponse> => {
    return apiClient.get(`/api/articles/tag/${data.tagName}`, { params: data });
  },
  deleteArticle: async (data: DeleteArticleRequest): Promise<void> => {
    return apiClient.delete(`/api/articles/${data.id}`);
  },
  toggleLike: async (data: ToggleLikeRequest): Promise<ToggleLikeResponse> => {
    return apiClient.post(`/api/articles/${data.articleId}/like`);
  },
  getDraftArticles: async (data: GetDraftArticlesRequest): Promise<GetDraftArticlesResponse> => {
    return apiClient.get('/api/articles/drafts', { params: data });
  },
};

// Auth API
export const authApi = {
  signUp: async (data: SignUpRequest): Promise<AuthResponse> => {
    return apiClient.post('/api/auth/signup', data);
  },
  signIn: async (data: SignInRequest): Promise<AuthResponse> => {
    return apiClient.post('/api/auth/signin', data);
  },
};

// Health API
export const healthApi = {
  getHealth: async (): Promise<GetHealthResponse> => {
    return apiClient.get('/api/health');
  },
};

// Users API
export const usersApi = {
  getUserProfile: async (data: GetUserProfileRequest): Promise<GetUserProfileResponse> => {
    return apiClient.get(`/api/users/${data.id}`, { params: data });
  },
  updateUserProfile: async (data: UpdateUserProfileRequest): Promise<UpdateUserProfileResponse> => {
    return apiClient.put('/api/users', data);
  },
};
