// Auto-generated by api-generator.py
// Do not edit manually

import { apiClient } from './client';
import type {
  AuthResponse,
  CreateArticleRequest,
  GetArticlesByAuthorResponse,
  GetArticlesByTagResponse,
  SignInRequest,
  SignUpRequest,
  UpdateArticleRequest,
  UpdateUserProfileRequest,
} from './types';

// Articles API
export const articlesApi = {
  createArticle: async (data: CreateArticleRequest): Promise<void> => {
    const response = await apiClient.post<void>('/api/articles', data);
    return response.data;
  },
  getArticle: async (): Promise<void> => {
    const response = await apiClient.get<void>('/api/articles/{id}');
    return response.data;
  },
  updateArticle: async (data: UpdateArticleRequest): Promise<void> => {
    const response = await apiClient.put<void>('/api/articles/{id}', data);
    return response.data;
  },
  getArticlesByAuthor: async (): Promise<GetArticlesByAuthorResponse> => {
    const response = await apiClient.get<GetArticlesByAuthorResponse>('/api/articles/author/{authorId}');
    return response.data;
  },
  getArticlesByTag: async (): Promise<GetArticlesByTagResponse> => {
    const response = await apiClient.get<GetArticlesByTagResponse>('/api/articles/tag/{tagName}');
    return response.data;
  },
  deleteArticle: async (): Promise<void> => {
    await apiClient.delete('/api/articles/{id}');
  },
  toggleLike: async (): Promise<void> => {
    const response = await apiClient.post<void>('/api/articles/{id}/like');
    return response.data;
  },
};

// Auth API
export const authApi = {
  signUp: async (data: SignUpRequest): Promise<AuthResponse> => {
    const response = await apiClient.post<AuthResponse>('/api/auth/signup', data);
    return response.data;
  },
  signIn: async (data: SignInRequest): Promise<AuthResponse> => {
    const response = await apiClient.post<AuthResponse>('/api/auth/signin', data);
    return response.data;
  },
};

// Health API
export const healthApi = {
  getHealth: async (): Promise<void> => {
    const response = await apiClient.get<void>('/api/health');
    return response.data;
  },
};

// Users API
export const usersApi = {
  getUserProfile: async (): Promise<void> => {
    const response = await apiClient.get<void>('/api/users/{id}');
    return response.data;
  },
  updateUserProfile: async (data: UpdateUserProfileRequest): Promise<void> => {
    const response = await apiClient.put<void>('/api/users', data);
    return response.data;
  },
};
