// Auto-generated React Query hooks
// DO NOT EDIT MANUALLY - generated by api-generator.py

import { useQuery, useMutation, type UseQueryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { articlesApi, authApi, healthApi, usersApi } from './endpoints';
import type {
  AuthResponse,
  CreateArticleRequest,
  CreateArticleResponse,
  DeleteArticleRequest,
  GetArticleRequest,
  GetArticleResponse,
  GetArticlesByAuthorRequest,
  GetArticlesByAuthorResponse,
  GetArticlesByTagRequest,
  GetArticlesByTagResponse,
  GetArticlesRequest,
  GetArticlesResponse,
  GetDraftArticlesRequest,
  GetDraftArticlesResponse,
  GetHealthResponse,
  GetUserProfileRequest,
  GetUserProfileResponse,
  SignInRequest,
  SignUpRequest,
  ToggleLikeRequest,
  ToggleLikeResponse,
  UpdateArticleRequest,
  UpdateArticleResponse,
  UpdateUserProfileRequest,
  UpdateUserProfileResponse,
} from './types';

// Query Keys
export const queryKeys = {
  articles: {
    getArticles: ['articles', 'getArticles'] as const,
    getArticle: ['articles', 'getArticle'] as const,
    getArticlesByAuthor: ['articles', 'getArticlesByAuthor'] as const,
    getArticlesByTag: ['articles', 'getArticlesByTag'] as const,
    getDraftArticles: ['articles', 'getDraftArticles'] as const,
  },
  auth: {
  },
  health: {
    getHealth: ['health', 'getHealth'] as const,
  },
  users: {
    getUserProfile: ['users', 'getUserProfile'] as const,
  },
};

// Articles Hooks
export function useGetArticles(data: GetArticlesRequest, options?: Omit<UseQueryOptions<GetArticlesResponse>, 'queryKey' | 'queryFn'>) {
  return useQuery({
    queryKey: [...queryKeys.articles.getArticles, data],
    queryFn: () => articlesApi.getArticles(data),
    ...options,
  });
}

export function useCreateArticle(options?: UseMutationOptions<CreateArticleResponse, Error, CreateArticleRequest>) {
  return useMutation({
    mutationFn: (data: CreateArticleRequest) => articlesApi.createArticle(data),
    ...options,
  });
}

export function useGetArticle(data: GetArticleRequest, options?: Omit<UseQueryOptions<GetArticleResponse>, 'queryKey' | 'queryFn'>) {
  return useQuery({
    queryKey: [...queryKeys.articles.getArticle, data],
    queryFn: () => articlesApi.getArticle(data),
    ...options,
  });
}

export function useUpdateArticle(options?: UseMutationOptions<UpdateArticleResponse, Error, UpdateArticleRequest>) {
  return useMutation({
    mutationFn: (data: UpdateArticleRequest) => articlesApi.updateArticle(data),
    ...options,
  });
}

export function useGetArticlesByAuthor(data: GetArticlesByAuthorRequest, options?: Omit<UseQueryOptions<GetArticlesByAuthorResponse>, 'queryKey' | 'queryFn'>) {
  return useQuery({
    queryKey: [...queryKeys.articles.getArticlesByAuthor, data],
    queryFn: () => articlesApi.getArticlesByAuthor(data),
    ...options,
  });
}

export function useGetArticlesByTag(data: GetArticlesByTagRequest, options?: Omit<UseQueryOptions<GetArticlesByTagResponse>, 'queryKey' | 'queryFn'>) {
  return useQuery({
    queryKey: [...queryKeys.articles.getArticlesByTag, data],
    queryFn: () => articlesApi.getArticlesByTag(data),
    ...options,
  });
}

export function useDeleteArticle(options?: UseMutationOptions<void, Error, DeleteArticleRequest>) {
  return useMutation({
    mutationFn: (data: DeleteArticleRequest) => articlesApi.deleteArticle(data),
    ...options,
  });
}

export function useToggleLike(options?: UseMutationOptions<ToggleLikeResponse, Error, ToggleLikeRequest>) {
  return useMutation({
    mutationFn: (data: ToggleLikeRequest) => articlesApi.toggleLike(data),
    ...options,
  });
}

export function useGetDraftArticles(data: GetDraftArticlesRequest, options?: Omit<UseQueryOptions<GetDraftArticlesResponse>, 'queryKey' | 'queryFn'>) {
  return useQuery({
    queryKey: [...queryKeys.articles.getDraftArticles, data],
    queryFn: () => articlesApi.getDraftArticles(data),
    ...options,
  });
}

// Auth Hooks
export function useSignUp(options?: UseMutationOptions<AuthResponse, Error, SignUpRequest>) {
  return useMutation({
    mutationFn: (data: SignUpRequest) => authApi.signUp(data),
    ...options,
  });
}

export function useSignIn(options?: UseMutationOptions<AuthResponse, Error, SignInRequest>) {
  return useMutation({
    mutationFn: (data: SignInRequest) => authApi.signIn(data),
    ...options,
  });
}

// Health Hooks
export function useGetHealth(options?: Omit<UseQueryOptions<GetHealthResponse>, 'queryKey' | 'queryFn'>) {
  return useQuery({
    queryKey: queryKeys.health.getHealth,
    queryFn: () => healthApi.getHealth(),
    ...options,
  });
}

// Users Hooks
export function useGetUserProfile(data: GetUserProfileRequest, options?: Omit<UseQueryOptions<GetUserProfileResponse>, 'queryKey' | 'queryFn'>) {
  return useQuery({
    queryKey: [...queryKeys.users.getUserProfile, data],
    queryFn: () => usersApi.getUserProfile(data),
    ...options,
  });
}

export function useUpdateUserProfile(options?: UseMutationOptions<UpdateUserProfileResponse, Error, UpdateUserProfileRequest>) {
  return useMutation({
    mutationFn: (data: UpdateUserProfileRequest) => usersApi.updateUserProfile(data),
    ...options,
  });
}
