// Auto-generated by api-generator.py
// Do not edit manually

import { useMutation, useQuery, useQueryClient, type UseMutationOptions, type UseQueryOptions } from '@tanstack/react-query';
import { articlesApi, authApi, coursesApi, healthApi, tagsApi, usersApi } from './endpoints';
import type {
  AuthResponse,
  CreateArticleRequest,
  CreateArticleResponse,
  CreateCommentRequest,
  CreateCommentResponse,
  CreateCourseRequest,
  CreateCourseResponse,
  DeleteArticleRequest,
  DeleteCourseRequest,
  GetArticleContentRequest,
  GetArticleContentResponse,
  GetArticlesByAuthorRequest,
  GetArticlesByAuthorResponse,
  GetArticlesByTagRequest,
  GetArticlesByTagResponse,
  GetArticlesRequest,
  GetArticlesResponse,
  GetCourseContentResponse,
  GetCoursesRequest,
  GetCoursesResponse,
  GetCurrentUserRequest,
  GetDraftArticlesRequest,
  GetDraftArticlesResponse,
  GetFollowersRequest,
  GetFollowersResponse,
  GetFollowingsRequest,
  GetFollowingsResponse,
  GetHealthResponse,
  GetLikedArticlesRequest,
  GetLikedArticlesResponse,
  GetPopularTagsRequest,
  GetPopularTagsResponse,
  GetUserProfileRequest,
  GetUserProfileResponse,
  SearchArticlesRequest,
  SearchArticlesResponse,
  SignInRequest,
  SignUpRequest,
  ToggleFollowRequest,
  ToggleFollowResponse,
  ToggleLikeRequest,
  ToggleLikeResponse,
  UpdateArticleRequest,
  UpdateArticleResponse,
  UpdateCourseRequest,
  UpdateCourseResponse,
  UpdateUserProfileRequest,
  UpdateUserProfileResponse,
} from './types';

// Query Keys
export const queryKeys = {
  articles: {
    getArticles: ['articles', 'getArticles'] as const,
    getArticleContent: ['articles', 'getArticleContent'] as const,
    getArticlesByAuthor: ['articles', 'getArticlesByAuthor'] as const,
    getArticlesByTag: ['articles', 'getArticlesByTag'] as const,
    getDraftArticles: ['articles', 'getDraftArticles'] as const,
    searchArticles: ['articles', 'searchArticles'] as const,
  },
  auth: {
    getCurrentUser: ['auth', 'getCurrentUser'] as const,
  },
  courses: {
    getCourses: ['courses', 'getCourses'] as const,
    getCourse: ['courses', 'getCourse'] as const,
  },
  health: {
    getHealth: ['health', 'getHealth'] as const,
  },
  tags: {
    getPopularTags: ['tags', 'getPopularTags'] as const,
  },
  users: {
    getUserProfile: ['users', 'getUserProfile'] as const,
    getFollowers: ['users', 'getFollowers'] as const,
    getFollowings: ['users', 'getFollowings'] as const,
    getLikedArticles: ['users', 'getLikedArticles'] as const,
  },
};

// Articles Hooks
export function useGetArticles(params: GetArticlesRequest, options?: Omit<UseQueryOptions<GetArticlesResponse>, 'queryKey' | 'queryFn'>) {
  return useQuery<GetArticlesResponse>({
    queryKey: [...queryKeys.articles.getArticles, params],
    queryFn: () => articlesApi.getArticles(params),
    ...options,
  });
}

export function useCreateArticle(options?: UseMutationOptions<CreateArticleResponse, Error, CreateArticleRequest>) {
  const queryClient = useQueryClient();
  return useMutation<CreateArticleResponse, Error, CreateArticleRequest>({
    mutationFn: (data) => articlesApi.createArticle(data),
    onSuccess: (...args) => {
      queryClient.invalidateQueries({ queryKey: ['articles'] });
      options?.onSuccess?.(...args);
    },
    ...options,
  });
}

export function useGetArticleContent(params: GetArticleContentRequest, options?: Omit<UseQueryOptions<GetArticleContentResponse>, 'queryKey' | 'queryFn'>) {
  return useQuery<GetArticleContentResponse>({
    queryKey: [...queryKeys.articles.getArticleContent, params],
    queryFn: () => articlesApi.getArticleContent(params),
    ...options,
  });
}

export function useUpdateArticle(options?: UseMutationOptions<UpdateArticleResponse, Error, UpdateArticleRequest>) {
  const queryClient = useQueryClient();
  return useMutation<UpdateArticleResponse, Error, UpdateArticleRequest>({
    mutationFn: (data) => articlesApi.updateArticle(data),
    onSuccess: (...args) => {
      queryClient.invalidateQueries({ queryKey: ['articles'] });
      options?.onSuccess?.(...args);
    },
    ...options,
  });
}

export function useGetArticlesByAuthor(params: GetArticlesByAuthorRequest, options?: Omit<UseQueryOptions<GetArticlesByAuthorResponse>, 'queryKey' | 'queryFn'>) {
  return useQuery<GetArticlesByAuthorResponse>({
    queryKey: [...queryKeys.articles.getArticlesByAuthor, params],
    queryFn: () => articlesApi.getArticlesByAuthor(params),
    ...options,
  });
}

export function useGetArticlesByTag(params: GetArticlesByTagRequest, options?: Omit<UseQueryOptions<GetArticlesByTagResponse>, 'queryKey' | 'queryFn'>) {
  return useQuery<GetArticlesByTagResponse>({
    queryKey: [...queryKeys.articles.getArticlesByTag, params],
    queryFn: () => articlesApi.getArticlesByTag(params),
    ...options,
  });
}

export function useDeleteArticle(options?: UseMutationOptions<void, Error, DeleteArticleRequest>) {
  const queryClient = useQueryClient();
  return useMutation<void, Error, DeleteArticleRequest>({
    mutationFn: (data) => articlesApi.deleteArticle(data),
    onSuccess: (...args) => {
      queryClient.invalidateQueries({ queryKey: ['articles'] });
      options?.onSuccess?.(...args);
    },
    ...options,
  });
}

export function useToggleLike(options?: UseMutationOptions<ToggleLikeResponse, Error, ToggleLikeRequest>) {
  const queryClient = useQueryClient();
  return useMutation<ToggleLikeResponse, Error, ToggleLikeRequest>({
    mutationFn: (data) => articlesApi.toggleLike(data),
    onSuccess: (...args) => {
      queryClient.invalidateQueries({ queryKey: ['articles'] });
      options?.onSuccess?.(...args);
    },
    ...options,
  });
}

export function useGetDraftArticles(params: GetDraftArticlesRequest, options?: Omit<UseQueryOptions<GetDraftArticlesResponse>, 'queryKey' | 'queryFn'>) {
  return useQuery<GetDraftArticlesResponse>({
    queryKey: [...queryKeys.articles.getDraftArticles, params],
    queryFn: () => articlesApi.getDraftArticles(params),
    ...options,
  });
}

export function useSearchArticles(params: SearchArticlesRequest, options?: Omit<UseQueryOptions<SearchArticlesResponse>, 'queryKey' | 'queryFn'>) {
  return useQuery<SearchArticlesResponse>({
    queryKey: [...queryKeys.articles.searchArticles, params],
    queryFn: () => articlesApi.searchArticles(params),
    ...options,
  });
}

export function useCreateComment(options?: UseMutationOptions<CreateCommentResponse, Error, CreateCommentRequest>) {
  const queryClient = useQueryClient();
  return useMutation<CreateCommentResponse, Error, CreateCommentRequest>({
    mutationFn: (data) => articlesApi.createComment(data),
    onSuccess: (...args) => {
      queryClient.invalidateQueries({ queryKey: ['articles'] });
      options?.onSuccess?.(...args);
    },
    ...options,
  });
}

// Auth Hooks
export function useSignUp(options?: UseMutationOptions<AuthResponse, Error, SignUpRequest>) {
  const queryClient = useQueryClient();
  return useMutation<AuthResponse, Error, SignUpRequest>({
    mutationFn: (data) => authApi.signUp(data),
    onSuccess: (...args) => {
      queryClient.invalidateQueries({ queryKey: ['auth'] });
      options?.onSuccess?.(...args);
    },
    ...options,
  });
}

export function useSignIn(options?: UseMutationOptions<AuthResponse, Error, SignInRequest>) {
  const queryClient = useQueryClient();
  return useMutation<AuthResponse, Error, SignInRequest>({
    mutationFn: (data) => authApi.signIn(data),
    onSuccess: (...args) => {
      queryClient.invalidateQueries({ queryKey: ['auth'] });
      options?.onSuccess?.(...args);
    },
    ...options,
  });
}

export function useGetCurrentUser(params: GetCurrentUserRequest, options?: Omit<UseQueryOptions<AuthResponse>, 'queryKey' | 'queryFn'>) {
  return useQuery<AuthResponse>({
    queryKey: [...queryKeys.auth.getCurrentUser, params],
    queryFn: () => authApi.getCurrentUser(params),
    ...options,
  });
}

export function useLogout(options?: UseMutationOptions<void, Error, void>) {
  const queryClient = useQueryClient();
  return useMutation<void, Error, void>({
    mutationFn: () => authApi.logout(),
    onSuccess: (...args) => {
      queryClient.invalidateQueries({ queryKey: ['auth'] });
      options?.onSuccess?.(...args);
    },
    ...options,
  });
}

// Courses Hooks
export function useGetCourses(params: GetCoursesRequest, options?: Omit<UseQueryOptions<GetCoursesResponse>, 'queryKey' | 'queryFn'>) {
  return useQuery<GetCoursesResponse>({
    queryKey: [...queryKeys.courses.getCourses, params],
    queryFn: () => coursesApi.getCourses(params),
    ...options,
  });
}

export function useCreateCourse(options?: UseMutationOptions<CreateCourseResponse, Error, CreateCourseRequest>) {
  const queryClient = useQueryClient();
  return useMutation<CreateCourseResponse, Error, CreateCourseRequest>({
    mutationFn: (data) => coursesApi.createCourse(data),
    onSuccess: (...args) => {
      queryClient.invalidateQueries({ queryKey: ['courses'] });
      options?.onSuccess?.(...args);
    },
    ...options,
  });
}

export function useGetCourse(options?: Omit<UseQueryOptions<GetCourseContentResponse>, 'queryKey' | 'queryFn'>) {
  return useQuery<GetCourseContentResponse>({
    queryKey: queryKeys.courses.getCourse,
    queryFn: () => coursesApi.getCourse(),
    ...options,
  });
}

export function useDeleteCourse(options?: UseMutationOptions<void, Error, DeleteCourseRequest>) {
  const queryClient = useQueryClient();
  return useMutation<void, Error, DeleteCourseRequest>({
    mutationFn: (data) => coursesApi.deleteCourse(data),
    onSuccess: (...args) => {
      queryClient.invalidateQueries({ queryKey: ['courses'] });
      options?.onSuccess?.(...args);
    },
    ...options,
  });
}

export function useUpdateCourse(options?: UseMutationOptions<UpdateCourseResponse, Error, UpdateCourseRequest>) {
  const queryClient = useQueryClient();
  return useMutation<UpdateCourseResponse, Error, UpdateCourseRequest>({
    mutationFn: (data) => coursesApi.updateCourse(data),
    onSuccess: (...args) => {
      queryClient.invalidateQueries({ queryKey: ['courses'] });
      options?.onSuccess?.(...args);
    },
    ...options,
  });
}

// Health Hooks
export function useGetHealth(options?: Omit<UseQueryOptions<GetHealthResponse>, 'queryKey' | 'queryFn'>) {
  return useQuery<GetHealthResponse>({
    queryKey: queryKeys.health.getHealth,
    queryFn: () => healthApi.getHealth(),
    ...options,
  });
}

// Tags Hooks
export function useGetPopularTags(params: GetPopularTagsRequest, options?: Omit<UseQueryOptions<GetPopularTagsResponse>, 'queryKey' | 'queryFn'>) {
  return useQuery<GetPopularTagsResponse>({
    queryKey: [...queryKeys.tags.getPopularTags, params],
    queryFn: () => tagsApi.getPopularTags(params),
    ...options,
  });
}

// Users Hooks
export function useGetUserProfile(params: GetUserProfileRequest, options?: Omit<UseQueryOptions<GetUserProfileResponse>, 'queryKey' | 'queryFn'>) {
  return useQuery<GetUserProfileResponse>({
    queryKey: [...queryKeys.users.getUserProfile, params],
    queryFn: () => usersApi.getUserProfile(params),
    ...options,
  });
}

export function useUpdateUserProfile(options?: UseMutationOptions<UpdateUserProfileResponse, Error, UpdateUserProfileRequest>) {
  const queryClient = useQueryClient();
  return useMutation<UpdateUserProfileResponse, Error, UpdateUserProfileRequest>({
    mutationFn: (data) => usersApi.updateUserProfile(data),
    onSuccess: (...args) => {
      queryClient.invalidateQueries({ queryKey: ['users'] });
      options?.onSuccess?.(...args);
    },
    ...options,
  });
}

export function useToggleFollow(options?: UseMutationOptions<ToggleFollowResponse, Error, ToggleFollowRequest>) {
  const queryClient = useQueryClient();
  return useMutation<ToggleFollowResponse, Error, ToggleFollowRequest>({
    mutationFn: (data) => usersApi.toggleFollow(data),
    onSuccess: (...args) => {
      queryClient.invalidateQueries({ queryKey: ['users'] });
      options?.onSuccess?.(...args);
    },
    ...options,
  });
}

export function useGetFollowers(params: GetFollowersRequest, options?: Omit<UseQueryOptions<GetFollowersResponse>, 'queryKey' | 'queryFn'>) {
  return useQuery<GetFollowersResponse>({
    queryKey: [...queryKeys.users.getFollowers, params],
    queryFn: () => usersApi.getFollowers(params),
    ...options,
  });
}

export function useGetFollowings(params: GetFollowingsRequest, options?: Omit<UseQueryOptions<GetFollowingsResponse>, 'queryKey' | 'queryFn'>) {
  return useQuery<GetFollowingsResponse>({
    queryKey: [...queryKeys.users.getFollowings, params],
    queryFn: () => usersApi.getFollowings(params),
    ...options,
  });
}

export function useGetLikedArticles(params: GetLikedArticlesRequest, options?: Omit<UseQueryOptions<GetLikedArticlesResponse>, 'queryKey' | 'queryFn'>) {
  return useQuery<GetLikedArticlesResponse>({
    queryKey: [...queryKeys.users.getLikedArticles, params],
    queryFn: () => usersApi.getLikedArticles(params),
    ...options,
  });
}
