// Auto-generated by api-generator.py
// Do not edit manually
// Server-side fetch functions for Next.js Server Components

import { getEnv } from '../../../utils/env';

function getBaseUrl(): string {
  return getEnv('API_URL') || 'http://localhost:5243';
}

/**
 * サーバーサイド用のfetch関数（共通処理）
 */
async function serverFetch<T>(url: string): Promise<T> {
  const response = await fetch(url, {
    method: 'GET',
    headers: {
      'Content-Type': 'application/json',
    },
    cache: 'no-store', // Next.js: 常に最新のデータを取得
  });

  if (!response.ok) {
    throw new Error(`Failed to fetch: ${response.statusText}`);
  }

  return response.json();
}

import type {
  AuthResponse,
  GetArticleContentRequest,
  GetArticleContentResponse,
  GetArticlesByAuthorRequest,
  GetArticlesByAuthorResponse,
  GetArticlesByTagRequest,
  GetArticlesByTagResponse,
  GetArticlesRequest,
  GetArticlesResponse,
  GetCourseContentRequest,
  GetCourseContentResponse,
  GetCoursesByAuthorRequest,
  GetCoursesByAuthorResponse,
  GetCoursesRequest,
  GetCoursesResponse,
  GetCurrentUserRequest,
  GetDraftArticlesRequest,
  GetDraftArticlesResponse,
  GetFollowersRequest,
  GetFollowersResponse,
  GetFollowingsRequest,
  GetFollowingsResponse,
  GetHealthResponse,
  GetLikedArticlesRequest,
  GetLikedArticlesResponse,
  GetMyCoursesResponse,
  GetPopularTagsRequest,
  GetPopularTagsResponse,
  GetUserProfileRequest,
  GetUserProfileResponse,
  SearchArticlesRequest,
  SearchArticlesResponse,
  SearchCoursesRequest,
  SearchCoursesResponse,
} from './types';

// Articles Server Functions
export async function getArticles(params: GetArticlesRequest): Promise<GetArticlesResponse> {
  const url = new URL('/api/articles', getBaseUrl());
  Object.entries(params).forEach(([key, value]) => {
    if (value !== undefined && value !== null) {
      url.searchParams.append(key, String(value));
    }
  });

  return serverFetch<GetArticlesResponse>(url.toString());
}

export async function getArticleContent(params: GetArticleContentRequest): Promise<GetArticleContentResponse> {
  const url = `${getBaseUrl()}/api/articles/${params.id}`;

  return serverFetch<GetArticleContentResponse>(url);
}

export async function getArticlesByAuthor(params: GetArticlesByAuthorRequest): Promise<GetArticlesByAuthorResponse> {
  const url = `${getBaseUrl()}/api/articles/author/${params.authorId}`;

  return serverFetch<GetArticlesByAuthorResponse>(url);
}

export async function getArticlesByTag(params: GetArticlesByTagRequest): Promise<GetArticlesByTagResponse> {
  const url = `${getBaseUrl()}/api/articles/tag/${params.tagName}`;

  return serverFetch<GetArticlesByTagResponse>(url);
}

export async function getDraftArticles(params: GetDraftArticlesRequest): Promise<GetDraftArticlesResponse> {
  const url = new URL('/api/articles/drafts', getBaseUrl());
  Object.entries(params).forEach(([key, value]) => {
    if (value !== undefined && value !== null) {
      url.searchParams.append(key, String(value));
    }
  });

  return serverFetch<GetDraftArticlesResponse>(url.toString());
}

export async function searchArticles(params: SearchArticlesRequest): Promise<SearchArticlesResponse> {
  const url = new URL('/api/articles/search', getBaseUrl());
  Object.entries(params).forEach(([key, value]) => {
    if (value !== undefined && value !== null) {
      url.searchParams.append(key, String(value));
    }
  });

  return serverFetch<SearchArticlesResponse>(url.toString());
}

// Auth Server Functions
export async function getCurrentUser(params: GetCurrentUserRequest): Promise<AuthResponse> {
  const url = new URL('/api/auth/me', getBaseUrl());
  Object.entries(params).forEach(([key, value]) => {
    if (value !== undefined && value !== null) {
      url.searchParams.append(key, String(value));
    }
  });

  return serverFetch<AuthResponse>(url.toString());
}

// Courses Server Functions
export async function getCourses(params: GetCoursesRequest): Promise<GetCoursesResponse> {
  const url = new URL('/api/courses', getBaseUrl());
  Object.entries(params).forEach(([key, value]) => {
    if (value !== undefined && value !== null) {
      url.searchParams.append(key, String(value));
    }
  });

  return serverFetch<GetCoursesResponse>(url.toString());
}

export async function searchCourses(params: SearchCoursesRequest): Promise<SearchCoursesResponse> {
  const url = new URL('/api/courses/search', getBaseUrl());
  Object.entries(params).forEach(([key, value]) => {
    if (value !== undefined && value !== null) {
      url.searchParams.append(key, String(value));
    }
  });

  return serverFetch<SearchCoursesResponse>(url.toString());
}

export async function getMyCourses(): Promise<GetMyCoursesResponse> {
  const url = `${getBaseUrl()}/api/courses/my`;

  return serverFetch<GetMyCoursesResponse>(url);
}

export async function getCoursesByAuthor(params: GetCoursesByAuthorRequest): Promise<GetCoursesByAuthorResponse> {
  const url = `${getBaseUrl()}/api/courses/author/${params.authorId}`;

  return serverFetch<GetCoursesByAuthorResponse>(url);
}

export async function getCourseContent(params: GetCourseContentRequest): Promise<GetCourseContentResponse> {
  const url = `${getBaseUrl()}/api/courses/${params.id}`;

  return serverFetch<GetCourseContentResponse>(url);
}

export async function getCourseContentForEdit(): Promise<GetCourseContentResponse> {
  const url = `${getBaseUrl()}/api/courses/${params.id}/for-edit`;

  return serverFetch<GetCourseContentResponse>(url);
}

// Health Server Functions
export async function getHealth(): Promise<GetHealthResponse> {
  const url = `${getBaseUrl()}/api/health`;

  return serverFetch<GetHealthResponse>(url);
}

// Tags Server Functions
export async function getPopularTags(params: GetPopularTagsRequest): Promise<GetPopularTagsResponse> {
  const url = new URL('/api/tags/popular', getBaseUrl());
  Object.entries(params).forEach(([key, value]) => {
    if (value !== undefined && value !== null) {
      url.searchParams.append(key, String(value));
    }
  });

  return serverFetch<GetPopularTagsResponse>(url.toString());
}

// Users Server Functions
export async function getUserProfile(params: GetUserProfileRequest): Promise<GetUserProfileResponse> {
  const url = `${getBaseUrl()}/api/users/${params.id}`;

  return serverFetch<GetUserProfileResponse>(url);
}

export async function getFollowers(params: GetFollowersRequest): Promise<GetFollowersResponse> {
  const url = `${getBaseUrl()}/api/users/${params.userId}/followers`;

  return serverFetch<GetFollowersResponse>(url);
}

export async function getFollowings(params: GetFollowingsRequest): Promise<GetFollowingsResponse> {
  const url = `${getBaseUrl()}/api/users/${params.userId}/followings`;

  return serverFetch<GetFollowingsResponse>(url);
}

export async function getLikedArticles(params: GetLikedArticlesRequest): Promise<GetLikedArticlesResponse> {
  const url = `${getBaseUrl()}/api/users/${params.userId}/liked-articles`;

  return serverFetch<GetLikedArticlesResponse>(url);
}
