// Auto-generated by api-generator.py
// Do not edit manually


export interface ArticleDto {
  id: number;
  title: string;
  body: string;
  authorId: number;
  authorName: string;
  tags: string[];
  likeCount: number;
  isPublished: boolean;
  publishedAt?: string;
  createdAt: string;
  updatedAt: string;
}

export interface AuthResponse {
  userId?: number;
  userName?: string;
}

export interface CommentDto {
  id: number;
  userId: number;
  userName: string;
  message: string;
  createdAt: string;
}

export interface CourseArticleDto {
  id: number;
  title: string;
  articleOrder?: number;
  isPublished: boolean;
}

export interface CourseDto {
  id: number;
  userId: number;
  userName?: string;
  name: string;
  articleIds: number[];
  articleNames: string[];
  likeCount: number;
  isPublished: boolean;
  publishedAt?: string;
}

export interface CreateArticleRequest {
  title: string;
  body: string;
  authorId: number;
  courseId?: number;
  articleOrder?: number;
  tags: string[];
  isPublished: boolean;
  publishedAt?: string;
}

export interface CreateArticleResponse {
  id: number;
  createdAt: string;
}

export interface CreateCommentRequest {
  articleId: number;
  message: string;
}

export interface CreateCommentResponse {
  id: number;
  createdAt: string;
}

export interface CreateCourseRequest {
  name: string;
}

export interface CreateCourseResponse {
  course: CourseDto;
}

export interface DeleteArticleRequest {
  id: number;
}

export interface DeleteCourseRequest {
  id: number;
}

export interface ErrorResponse {
  statusCode: number;
  message: string;
  timeStamp: string;
}

export interface FollowerUserDto {
  id: number;
  username: string;
  profileImage?: string;
}

export interface GetArticleContentRequest {
  id: number;
}

export interface GetArticleContentResponse {
  id: number;
  title: string;
  body: string;
  authorId: number;
  authorName: string;
  tags: string[];
  likeCount: number;
  isLiked: boolean;
  isPublished: boolean;
  publishedAt?: string;
  createdAt: string;
  updatedAt: string;
  comments: CommentDto[];
  courseId?: number;
  courseName?: string;
}

export interface GetArticlesByAuthorRequest {
  authorId: number;
}

export interface GetArticlesByAuthorResponse {
  authorId: number;
  authorName: string;
  articles: ArticleDto[];
  totalCount: number;
}

export interface GetArticlesByTagRequest {
  tagName: string;
}

export interface GetArticlesByTagResponse {
  articles: ArticleDto[];
}

export interface GetArticlesRequest {
  limit: number;
  offset: number;
}

export interface GetArticlesResponse {
  articles: ArticleDto[];
  totalCount: number;
}

export interface GetCourseContentRequest {
  id: number;
}

export interface GetCourseContentResponse {
  id: number;
  name: string;
  userId: number;
  userName: string;
  likeCount: number;
  isPublished: boolean;
  publishedAt?: string;
  createdAt: string;
  articles: CourseArticleDto[];
}

export interface GetCoursesByAuthorRequest {
  authorId: number;
}

export interface GetCoursesByAuthorResponse {
  authorId: number;
  authorName: string;
  courses: CourseDto[];
  totalCount: number;
}

export interface GetCoursesRequest {
  limit: number;
  offset: number;
}

export interface GetCoursesResponse {
  courses: CourseDto[];
  totalCount: number;
}

// eslint-disable-next-line @typescript-eslint/no-empty-object-type
export interface GetCurrentUserRequest {
}

// eslint-disable-next-line @typescript-eslint/no-empty-object-type
export interface GetDraftArticlesRequest {
}

export interface GetDraftArticlesResponse {
  articles: ArticleDto[];
}

export interface GetFollowersRequest {
  userId: number;
}

export interface GetFollowersResponse {
  followers: FollowerUserDto[];
}

export interface GetFollowingsRequest {
  userId: number;
}

export interface GetFollowingsResponse {
  followings: FollowerUserDto[];
}

export interface GetHealthResponse {
  statusCode: number;
  message: string;
}

export interface GetLikedArticlesRequest {
  userId: number;
}

export interface GetLikedArticlesResponse {
  userId: number;
  articles: ArticleDto[];
  totalCount: number;
}

// eslint-disable-next-line @typescript-eslint/no-empty-object-type
export interface GetPopularTagsRequest {
}

export interface GetPopularTagsResponse {
  tags: TagDto[];
}

export interface GetUserProfileRequest {
  id: number;
}

export interface GetUserProfileResponse {
  id: number;
  username: string;
  bio?: string;
  createdAt: string;
  followerCount: number;
  followingCount: number;
  isFollowing: boolean;
  articleCount: number;
  likedArticleCount: number;
}

// eslint-disable-next-line @typescript-eslint/no-empty-object-type
export interface HealthCheckRequest {
}

// eslint-disable-next-line @typescript-eslint/no-empty-object-type
export interface LogoutRequest {
}

export interface SearchArticlesRequest {
  keyword: string;
  limit: number;
  offset: number;
}

export interface SearchArticlesResponse {
  articles: ArticleDto[];
}

export interface SearchCoursesRequest {
  keyword: string;
  limit: number;
  offset: number;
}

export interface SearchCoursesResponse {
  courses: CourseDto[];
}

export interface SignInRequest {
  usernameOrEmail: string;
  password: string;
}

export interface SignUpRequest {
  name: string;
  email: string;
  password: string;
}

export interface TagDto {
  name: string;
  articleCount: number;
}

export interface ToggleFollowRequest {
  followingId: number;
}

export interface ToggleFollowResponse {
  isFollowing: boolean;
  currentFollowerCount: number;
}

export interface ToggleLikeRequest {
  articleId: number;
}

export interface ToggleLikeResponse {
  isLiked: boolean;
  currentLikeCount: number;
}

export interface UpdateArticleRequest {
  id: number;
  title?: string;
  body?: string;
  tags?: string[];
  isPublished?: boolean;
  publishedAt?: string;
  articleOrder?: number;
}

export interface UpdateArticleResponse {
  id: number;
  updatedAt: string;
}

export interface UpdateCourseRequest {
  id: number;
  name?: string;
  isPublished?: boolean;
  publishedAt?: string;
}

export interface UpdateCourseResponse {
  id: number;
  updatedAt: string;
}

export interface UpdateUserProfileRequest {
  name?: string;
  profileImage?: string;
  bio?: string;
}

// eslint-disable-next-line @typescript-eslint/no-empty-object-type
export interface UpdateUserProfileResponse {
}
