// Auto-generated by api-generator.py
// Do not edit manually


export interface ArticleDto {
  id?: number;
  title?: string;
  body?: string;
  authorId?: number;
  authorName?: string;
  tags?: string[];
  likeCount?: number;
  isPublished?: boolean;
  createdAt?: string;
  updatedAt?: string;
}

export interface AuthResponse {
  userId?: number;
}

export interface CreateArticleRequest {
  title?: string;
  body?: string;
  authorId?: number;
  tags?: string[];
  isPublished?: boolean;
}

export interface CreateArticleResponse {
  id?: number;
  createdAt?: string;
}

export interface DeleteArticleRequest {
  id?: number;
}

export interface ErrorResponse {
  statusCode?: number;
  message?: string;
  timeStamp?: string;
}

export interface GetArticleRequest {
  id?: number;
}

export interface GetArticleResponse {
  id?: number;
  title?: string;
  body?: string;
  authorId?: number;
  authorName?: string;
  tags?: string[];
  likeCount?: number;
  isPublished?: boolean;
  createdAt?: string;
  updatedAt?: string;
}

export interface GetArticlesByAuthorRequest {
  authorId?: number;
}

export interface GetArticlesByAuthorResponse {
  authorId?: number;
  authorName?: string;
  articles?: ArticleDto[];
  totalCount?: number;
}

export interface GetArticlesByTagRequest {
  tagName?: string;
}

export interface GetArticlesByTagResponse {
  articles?: ArticleDto[];
}

export interface GetArticlesRequest {
  limit?: number;
  offset?: number;
}

export interface GetArticlesResponse {
  articles?: ArticleDto[];
  totalCount?: number;
}

// eslint-disable-next-line @typescript-eslint/no-empty-object-type
export interface GetDraftArticlesRequest {
}

export interface GetDraftArticlesResponse {
  articles?: ArticleDto[];
}

export interface GetHealthResponse {
  statusCode?: number;
  message?: string;
}

export interface GetUserProfileRequest {
  id?: number;
}

export interface GetUserProfileResponse {
  id?: number;
  username?: string;
  bio?: string;
  createdAt?: string;
}

// eslint-disable-next-line @typescript-eslint/no-empty-object-type
export interface HealthCheckRequest {
}

export interface SignInRequest {
  usernameOrEmail?: string;
  password?: string;
}

export interface SignUpRequest {
  name?: string;
  email?: string;
  password?: string;
}

export interface ToggleFollowRequest {
  followingId?: number;
}

export interface ToggleFollowResponse {
  isFollowing?: boolean;
  currentFollowerCount?: number;
}

export interface ToggleLikeRequest {
  articleId?: number;
}

export interface ToggleLikeResponse {
  isLiked?: boolean;
  currentLikeCount?: number;
}

export interface UpdateArticleRequest {
  id?: number;
  title?: string;
  body?: string;
  tags?: string[];
  isPublished?: boolean;
}

export interface UpdateArticleResponse {
  id?: number;
  updatedAt?: string;
}

export interface UpdateUserProfileRequest {
  name?: string;
  profileImage?: string;
  bio?: string;
}

// eslint-disable-next-line @typescript-eslint/no-empty-object-type
export interface UpdateUserProfileResponse {
}
