// Auto-generated by api-generator.py
// Do not edit manually


export interface ArticleDto {
  id?: number;
  title?: string;
  body?: string;
  authorId?: number;
  authorName?: string;
  tags?: string[];
  likeCount?: number;
  isPublished?: boolean;
  publishedAt?: string;
  createdAt?: string;
  updatedAt?: string;
}

export interface AuthResponse {
  userId?: number;
}

export interface CommentDto {
  id?: number;
  userId?: number;
  userName?: string;
  message?: string;
  createdAt?: string;
}

export interface CourseDto {
  id?: number;
  userId?: number;
  name?: string;
  articleIds?: number[];
  articleNames?: string[];
  likeCount?: number;
}

export interface CreateArticleRequest {
  title?: string;
  body?: string;
  authorId?: number;
  tags?: string[];
  isPublished?: boolean;
  publishedAt?: string;
}

export interface CreateArticleResponse {
  id?: number;
  createdAt?: string;
}

export interface CreateCommentRequest {
  articleId?: number;
  message?: string;
}

export interface CreateCommentResponse {
  id?: number;
  createdAt?: string;
}

export interface CreateCourseRequest {
  name?: string;
}

export interface CreateCourseResponse {
  course?: CourseDto;
}

export interface DeleteArticleRequest {
  id?: number;
}

export interface ErrorResponse {
  statusCode?: number;
  message?: string;
  timeStamp?: string;
}

export interface FollowerUserDto {
  id?: number;
  username?: string;
  profileImage?: string;
}

export interface GetArticleRequest {
  id?: number;
}

export interface GetArticleResponse {
  id?: number;
  title?: string;
  body?: string;
  authorId?: number;
  authorName?: string;
  tags?: string[];
  likeCount?: number;
  isLiked?: boolean;
  isPublished?: boolean;
  publishedAt?: string;
  createdAt?: string;
  updatedAt?: string;
  comments?: CommentDto[];
}

export interface GetArticlesByAuthorRequest {
  authorId?: number;
}

export interface GetArticlesByAuthorResponse {
  authorId?: number;
  authorName?: string;
  articles?: ArticleDto[];
  totalCount?: number;
}

export interface GetArticlesByTagRequest {
  tagName?: string;
}

export interface GetArticlesByTagResponse {
  articles?: ArticleDto[];
}

export interface GetArticlesRequest {
  limit?: number;
  offset?: number;
}

export interface GetArticlesResponse {
  articles?: ArticleDto[];
  totalCount?: number;
}

// eslint-disable-next-line @typescript-eslint/no-empty-object-type
export interface GetCurrentUserRequest {
}

// eslint-disable-next-line @typescript-eslint/no-empty-object-type
export interface GetDraftArticlesRequest {
}

export interface GetDraftArticlesResponse {
  articles?: ArticleDto[];
}

export interface GetFollowersRequest {
  userId?: number;
}

export interface GetFollowersResponse {
  followers?: FollowerUserDto[];
}

export interface GetFollowingsRequest {
  userId?: number;
}

export interface GetFollowingsResponse {
  followings?: FollowerUserDto[];
}

export interface GetHealthResponse {
  statusCode?: number;
  message?: string;
}

export interface GetLikedArticlesRequest {
  userId?: number;
}

export interface GetLikedArticlesResponse {
  userId?: number;
  articles?: ArticleDto[];
  totalCount?: number;
}

// eslint-disable-next-line @typescript-eslint/no-empty-object-type
export interface GetPopularTagsRequest {
}

export interface GetPopularTagsResponse {
  tags?: TagDto[];
}

export interface GetUserProfileRequest {
  id?: number;
}

export interface GetUserProfileResponse {
  id?: number;
  username?: string;
  bio?: string;
  createdAt?: string;
  followerCount?: number;
  followingCount?: number;
  isFollowing?: boolean;
  articleCount?: number;
  likedArticleCount?: number;
}

// eslint-disable-next-line @typescript-eslint/no-empty-object-type
export interface HealthCheckRequest {
}

// eslint-disable-next-line @typescript-eslint/no-empty-object-type
export interface LogoutRequest {
}

export interface SearchArticlesRequest {
  keyword?: string;
  limit?: number;
  offset?: number;
}

export interface SearchArticlesResponse {
  articles?: ArticleDto[];
}

export interface SignInRequest {
  usernameOrEmail?: string;
  password?: string;
}

export interface SignUpRequest {
  name?: string;
  email?: string;
  password?: string;
}

export interface TagDto {
  name?: string;
  articleCount?: number;
}

export interface ToggleFollowRequest {
  followingId?: number;
}

export interface ToggleFollowResponse {
  isFollowing?: boolean;
  currentFollowerCount?: number;
}

export interface ToggleLikeRequest {
  articleId?: number;
}

export interface ToggleLikeResponse {
  isLiked?: boolean;
  currentLikeCount?: number;
}

export interface UpdateArticleRequest {
  id?: number;
  title?: string;
  body?: string;
  tags?: string[];
  isPublished?: boolean;
  publishedAt?: string;
}

export interface UpdateArticleResponse {
  id?: number;
  updatedAt?: string;
}

export interface UpdateUserProfileRequest {
  name?: string;
  profileImage?: string;
  bio?: string;
}

// eslint-disable-next-line @typescript-eslint/no-empty-object-type
export interface UpdateUserProfileResponse {
}
