name: Documentation Issue
description: ドキュメント関連のissue
title: "[DOCS] "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        ドキュメント関連のissueを作成します。
  - type: textarea
    id: description
    attributes:
      label: 説明
      description: issueの詳細を記述してください
      placeholder: issueの内容を記述してください
    validations:
      required: true
  - type: textarea
    id: completion-criteria
    attributes:
      label: 完了条件
      description: このissueが完了したと判断する基準を記述してください（「xxができる」という形式で記述してください）
      placeholder: 例：READMEにセットアップ手順が記載されている
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: 追加情報
      description: その他の関連情報やコンテキストがあれば記述してください
      placeholder: 追加情報を記述してください
    validations:
      required: false
