# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket = "nari-note-terraform"
    key    = "prod/deploy/bucket/terraform.tfstate"
    region = "ap-northeast-1"
  }
}
