#!/usr/bin/env python3

"""
Templates for generating TypeScript API client code
"""

# Header templates
TYPES_HEADER = """// Auto-generated TypeScript types from C# DTOs
// DO NOT EDIT MANUALLY - generated by api-generator.py
"""

ENDPOINTS_HEADER = """// Auto-generated API endpoint functions
// DO NOT EDIT MANUALLY - generated by api-generator.py

import { apiClient } from './client';
import type {
"""

HOOKS_HEADER = """// Auto-generated React Query hooks
// DO NOT EDIT MANUALLY - generated by api-generator.py

import { useQuery, useMutation, type UseQueryOptions, type UseMutationOptions } from '@tanstack/react-query';
"""


def generate_interface_declaration(name: str, has_properties: bool) -> str:
    """Generate TypeScript interface declaration"""
    return f"export interface {name} {{"


def generate_property_declaration(name: str, ts_type: str, is_optional: bool) -> str:
    """Generate TypeScript property declaration"""
    optional_mark = "?" if is_optional else ""
    # Convert PascalCase to camelCase
    camel_name = name[0].lower() + name[1:] if name else name
    return f"  {camel_name}{optional_mark}: {ts_type};"


def generate_api_function(
    func_name: str,
    request_type: str,
    response_type: str,
    method: str,
    url_expression: str,
    path_params: list,
    send_body: bool
) -> list:
    """Generate API function code"""
    lines = []
    
    # Function signature
    if request_type == "void":
        lines.append(f"  {func_name}: async (): Promise<{response_type}> => {{")
    else:
        lines.append(f"  {func_name}: async (data: {request_type}): Promise<{response_type}> => {{")
    
    # HTTP method call
    method_lower = method.lower()
    if method_lower == "get":
        if request_type == "void":
            lines.append(f"    return apiClient.{method_lower}({url_expression});")
        else:
            lines.append(f"    return apiClient.{method_lower}({url_expression}, {{ params: data }});")
    elif method_lower == "delete":
        lines.append(f"    return apiClient.{method_lower}({url_expression});")
    else:  # POST, PUT
        if send_body:
            lines.append(f"    return apiClient.{method_lower}({url_expression}, data);")
        else:
            lines.append(f"    return apiClient.{method_lower}({url_expression});")
    
    lines.append("  },")
    
    return lines


def generate_query_hook(
    hook_name: str,
    func_name: str,
    controller: str,
    request_type: str,
    return_type: str
) -> list:
    """Generate React Query hook for GET requests"""
    lines = []
    
    if request_type == "void":
        lines.append(f"export function {hook_name}(options?: Omit<UseQueryOptions<{return_type}>, 'queryKey' | 'queryFn'>) {{")
        lines.append(f"  return useQuery({{")
        lines.append(f"    queryKey: queryKeys.{controller}.{func_name},")
        lines.append(f"    queryFn: () => {controller}Api.{func_name}(),")
        lines.append(f"    ...options,")
        lines.append(f"  }});")
        lines.append(f"}}")
    else:
        lines.append(f"export function {hook_name}(data: {request_type}, options?: Omit<UseQueryOptions<{return_type}>, 'queryKey' | 'queryFn'>) {{")
        lines.append(f"  return useQuery({{")
        lines.append(f"    queryKey: [...queryKeys.{controller}.{func_name}, data],")
        lines.append(f"    queryFn: () => {controller}Api.{func_name}(data),")
        lines.append(f"    ...options,")
        lines.append(f"  }});")
        lines.append(f"}}")
    
    return lines


def generate_mutation_hook(
    hook_name: str,
    func_name: str,
    controller: str,
    request_type: str,
    response_type: str
) -> list:
    """Generate React Query hook for POST/PUT/DELETE requests"""
    lines = []
    
    if request_type == "void":
        lines.append(f"export function {hook_name}(options?: UseMutationOptions<{response_type}, Error, void>) {{")
        lines.append(f"  return useMutation({{")
        lines.append(f"    mutationFn: () => {controller}Api.{func_name}(),")
    else:
        lines.append(f"export function {hook_name}(options?: UseMutationOptions<{response_type}, Error, {request_type}>) {{")
        lines.append(f"  return useMutation({{")
        lines.append(f"    mutationFn: (data: {request_type}) => {controller}Api.{func_name}(data),")
    
    lines.append(f"    ...options,")
    lines.append(f"  }});")
    lines.append(f"}}")
    
    return lines
